---
- name: Launch k8s master
  hosts: localhost
  pre_tasks:
    - name: clear openstack routes
      command: "openstack router set --no-route {{ router_id }}"

    - name: Set variables
      set_fact:
        state: present
        routeruuid: "{{ router_id }}"
        subnetuuid: "{{ subnet_id }}"
  roles:
    - openstack-sgs
    - openstack-master

- name: Master preparation
  hosts: master
  pre_tasks:
    - name: Set variables
      set_fact:
        state: present
  tags:
    - bootstrap
  gather_facts: false
  become: true
  roles:
    - common
    - common-master

- name: Launch k8s nodes
  hosts: localhost
  roles:
    - openstack-nodes

- name: Nodes preparation
  hosts: nodes
  tags:
    - bootstrap
  gather_facts: false
  become: true
  roles:
    - common
    - common-nodes
