- name: Wait for cloud-init to finish
  raw: while ! test -f /var/lib/cloud/instance/boot-finished; do sleep 1; done
  retries: 5
  delay: 1
  tags:
    - skip_ansible_lint

- name: Setup
  action: setup

- name: install microk8s
  snap:
    name: microk8s
    classic: yes
    channel: "{{ microk8s_channel }}"

- name: alias kubectl
  shell: |
    snap alias microk8s.kubectl k
    snap alias microk8s.kubectl kubectl

- name: alias kubectl
  shell: |
    snap alias microk8s.kubectl k
    snap alias microk8s.kubectl kubectl

- name: enable alpha api
  lineinfile:
    path: /var/snap/microk8s/current/args/kube-apiserver
    line: '--runtime-config=settings.k8s.io/v1alpha1=true'

- name: enable pod presets
  lineinfile:
    path: /var/snap/microk8s/current/args/kube-apiserver
    line: '--enable-admission-plugins="PodPreset"'

- name: restart kube api server
  systemd:
    state: restarted
    daemon_reload: yes
    name: snap.microk8s.daemon-apiserver.service

# if https proxy is required
- name: containerd proxy
  lineinfile:
    path: /var/snap/microk8s/current/args/containerd-env
    regexp: '^HTTPS_PROXY='
    line: 'HTTPS_PROXY={{ proxy_env.https_proxy }}'
  when: proxy_env.https_proxy != ""

- name: restart containerd
  systemd:
    state: restarted
    daemon_reload: yes
    name: snap.microk8s.daemon-containerd.service
  when: proxy_env.https_proxy != ""

- name: export kubectl config file
  shell:
    chdir: $HOME/.kube
    cmd: kubectl config view --raw > config
  become: no
